server:
  port: {PORT:0}

spring:
  application:
    name: users-webservice
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  datasource:
    url: jdbc:mysql://localhost:3306/photo_app?serverTimezone=UTC
    username: partha
    password: password

  jpa:
    hibernate:
      ddl-auto: update


eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

  instance:
    preferIpAddress: true
    leaseRenewalIntervalInSeconds: 10
    metadataMap:
      instanceId: ${vcap.application.instance_id:${spring.application.name}:${spring.application.instance_id:${server.port}}}


api:
  gateway:
    ip: 192.168.0.22

token:
  expiry:
    value: 864000000


  secret:
    value: letmebeyoursecret

login:
  url:
    path: /users/login

management:
  endpoints:
    web:
      exposure:
        include: beans,health,routes,httpTrace,mappings


logging:
  level:
    com:
      example:
        ms:
          sample:
            photoappuserservice:
              client:
                AlbumServiceFeignClient : DEBUG

feign:
  hystrix:
    enabled: true
